version: '3'
services:
  n42c:
    image: n42c
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m -Djdk.tls.ephemeralDHKeySize=2048
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:5432/n42c
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=${COGNITO_URI}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=${COGNITO_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${COGNITO_SECRET}
      - JHIPSTER_SLEEP=50 # gives time for other services to boot before the application
    ports:
      - 8080:8080
